# Generated by Django 3.1.5 on 2021-02-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210218_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='max_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
