# Generated by Django 3.1.5 on 2021-02-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_max_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='starting_bid',
            new_name='bid_starting',
        ),
    ]
