# Generated by Django 3.1.5 on 2021-02-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210218_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_starting',
        ),
        migrations.AddField(
            model_name='bid',
            name='start_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
