# Generated by Django 3.1.5 on 2021-02-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210218_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='max_bid',
            new_name='bids',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='start_bid',
        ),
    ]
