# Generated by Django 3.1.5 on 2021-02-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comments_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
