# Generated by Django 3.1.5 on 2021-02-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
