# Generated by Django 3.1.5 on 2021-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auction_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('winning_bid', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
